# Generated by Django 4.1.6 on 2023-02-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='цвет чернил')),
                ('color_title', models.CharField(blank=True, max_length=20, verbose_name='название цвета')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, choices=[('I', 'IRON'), ('W', 'WOOD'), ('A', 'ACRIL'), ('R', 'RAGE')], max_length=20, verbose_name='материал')),
                ('mass', models.PositiveIntegerField(blank=True, default=50, verbose_name='масса изделия в граммах')),
                ('size', models.PositiveIntegerField(blank=True, default=25, verbose_name='длина изделия в сантиметрах')),
                ('model', models.CharField(blank=True, max_length=30, unique=True, verbose_name='название модели изделия')),
                ('ink_color', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.color', verbose_name='цвет чернил')),
            ],
            options={
                'verbose_name': 'ручка',
                'verbose_name_plural': 'ручки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, unique=True, verbose_name='склад')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, verbose_name='колличество изделий')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.pen', verbose_name='продукт')),
                ('store_title', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.stores', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ('-id',),
            },
        ),
    ]
