# Generated by Django 4.1.6 on 2023-02-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ink_color', models.CharField(choices=[('R', 'red'), ('G', 'green'), ('Y', 'yellow'), ('B', 'blue'), ('P', 'pink'), ('O', 'orange'), ('BL', 'black'), ('PU', 'purple')], default='blue', max_length=20, verbose_name='цвет чернил')),
                ('material', models.CharField(choices=[('I', 'IRON'), ('W', 'WOOD'), ('A', 'ACRIL'), ('R', 'RAGE')], default='ACRIL', max_length=20, verbose_name='материал')),
                ('mass', models.IntegerField(default=50, verbose_name='масса изделия в граммах')),
                ('size', models.IntegerField(default=25, verbose_name='длина изделия в сантиметрах')),
                ('model', models.CharField(max_length=30, unique=True, verbose_name='название модели изделия')),
            ],
            options={
                'verbose_name': 'ручка',
                'verbose_name_plural': 'ручки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='склад')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='колличество изделий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pen', verbose_name='продукт')),
                ('store_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stores', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ('-id',),
            },
        ),
    ]
